Update lock script

diff --git a/scripts/encrypt-files b/scripts/encrypt-files
--- a/scripts/encrypt-files
+++ b/scripts/encrypt-files
@@ -1,41 +1,52 @@
 #!/bin/bash
 
-# TODO: ADD CHECK FOR UPPERCASE CHARACTERS, IN CASE FAIL
+trap "echo Exited!; exit;" SIGINT SIGTERM
 
 path="$1"
 
 # Check if directory is specified
 if [[ -z $path ]]; then
-	echo "Add directory as argument like -> 'encrypt-files video-list'"
-	exit 1
+  echo "Add directory as argument like 'encrypt-files video-list'"
+  exit 1
 elif [[ ! -d $path ]]; then
-	echo "Specified path is not a directory"
-	exit 1
+  echo "Specified path is not a directory"
+  exit 1
 fi
 
 destdir=$path-encrypted
 # Create directory
 if [[ ! -e $destdir ]]; then
-	mkdir $destdir
-	echo "${destdir} directory created"
+  mkdir $destdir
+  echo "${destdir} directory created"
 fi
+
+# Input password
+read -s -p "Password:" psw
+echo
 
 # Loop over files in path
 for filepath in $path/*; do
-	# If is not a regular file
-	[[ ! -f $filepath ]] && continue
+  # Skip if is not a regular file
+  [[ ! -f $filepath ]] && continue
 
-	# From: /home/marco/file.txt
-	# To:   file.txt
-	filename="${filepath##*/}"
-	destpath=$destdir/$filename.gpg
-	
-	# If file is already encrypted skip
-	if [[ -e $destpath ]]; then
-		echo "[ Already exists ] ${filename}"
-		continue
-	fi
-	echo -en "\r[   Generating   ] ${filename}"
-	gpg --recipient marcodifran@gmail.com --output $destpath --encrypt $filepath
-	echo -en "\r[      Done      ] ${filename}\n"
+  # From: /home/marco/file.txt
+  # To:   file.txt
+  filename="${filepath##*/}"
+  # destpath=$destdir/$filename.gpg
+  destpath=$destdir/$filename.7z
+
+  # If file is already encrypted skip
+  if [[ -e $destpath ]]; then
+    # echo "[ Already exists ] ${filename}"
+    echo -en "[    Testing     ] ${filename}"
+    if ! 7z t -p"${psw}" $destpath > /dev/null; then
+      echo "There was an error extracting '$filename'"
+      exit 1
+    fi
+  else
+    echo -en "\r[   Generating   ] ${filename}"
+    # gpg --recipient marcodifran@gmail.com --output $destpath --encrypt $filepath
+    7z a $destpath $filepath -p"${psw}" > /dev/null
+  fi
+  echo -en "\r[      Done      ] ${filename}\n"
 done
